#!/usr/bin/env python3
"""
System Architecture Diagram Generator
"""

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text
from rich.layout import Layout
from rich.align import Align

def print_system_architecture():
    """Print the complete system architecture diagram."""
    console = Console()
    
    # Main system overview
    console.print("\n" + "="*100)
    console.print("🎤 ELEVENLABS MULTI-AGENT CONVERSATIONAL AI SYSTEM ARCHITECTURE", style="bold cyan")
    console.print("="*100)
    
    # Data Flow Diagram
    console.print("\n📊 DATA FLOW ARCHITECTURE:")
    console.print("┌─────────────────────────────────────────────────────────────────────────────────────────────┐")
    console.print("│                                    DATA FLOW DIAGRAM                                      │")
    console.print("├─────────────────────────────────────────────────────────────────────────────────────────────┤")
    console.print("│                                                                                             │")
    console.print("│  🎤 Microphone Input                                                                        │")
    console.print("│         ↓                                                                                   │")
    console.print("│  🔗 ElevenLabs WebSocket                                                                    │")
    console.print("│         ↓                                                                                   │")
    console.print("│  📝 Conversation Context Builder                                                             │")
    console.print("│         ↓                                                                                   │")
    console.print("│  🔄 LangGraph Flow Orchestrator                                                             │")
    console.print("│         ↓                                                                                   │")
    console.print("│  🤖 Multi-Agent Parallel Execution                                                          │")
    console.print("│         ↓                                                                                   │")
    console.print("│  🧠 Mem0 Consolidation Engine                                                               │")
    console.print("│         ↓                                                                                   │")
    console.print("│  📊 Strategic Output & Recommendations                                                      │")
    console.print("│                                                                                             │")
    console.print("└─────────────────────────────────────────────────────────────────────────────────────────────┘")
    
    # Agent Architecture
    console.print("\n🤖 AGENT ARCHITECTURE:")
    console.print("┌─────────────────────────────────────────────────────────────────────────────────────────────┐")
    console.print("│                                    AGENT SPECIALIZATION                                    │")
    console.print("├─────────────────────────────────────────────────────────────────────────────────────────────┤")
    console.print("│                                                                                             │")
    console.print("│  🔵 Intent Agent (Quen)                    🟡 Strategy Agent (GPT-4o)                    │")
    console.print("│  ├─ Primary Intent Analysis                ├─ Strategic Approach                           │")
    console.print("│  ├─ Customer Motivations                   ├─ Business Opportunities                       │")
    console.print("│  ├─ Intent Confidence                      ├─ Risk Factors                                 │")
    console.print("│  └─ Next Expected Actions                  └─ Value Proposition                            │")
    console.print("│                                                                                             │")
    console.print("│  🟢 Sentiment Agent (Quen)                 🟣 Learning Agent (GPT-4o)                    │")
    console.print("│  ├─ Emotional State Analysis               ├─ Pattern Recognition                          │")
    console.print("│  ├─ Sentiment Score                        ├─ Knowledge Extraction                         │")
    console.print("│  ├─ Trust Level Assessment                 ├─ Behavioral Trends                            │")
    console.print("│  └─ Engagement Level                       └─ Long-term Implications                       │")
    console.print("│                                                                                             │")
    console.print("│  🔴 Decision Agent (Quen)                                                                  │")
    console.print("│  ├─ Immediate Action Planning                                                              │")
    console.print("│  ├─ Action Priority Assessment                                                             │")
    console.print("│  ├─ Decision Confidence                                                                   │")
    console.print("│  └─ Alternative Actions                                                                    │")
    console.print("│                                                                                             │")
    console.print("└─────────────────────────────────────────────────────────────────────────────────────────────┘")
    
    # Memory Structure
    console.print("\n🧠 MEMORY ARCHITECTURE:")
    console.print("┌─────────────────────────────────────────────────────────────────────────────────────────────┐")
    console.print("│                                    MEMORY STRUCTURE                                        │")
    console.print("├─────────────────────────────────────────────────────────────────────────────────────────────┤")
    console.print("│                                                                                             │")
    console.print("│  📁 File System Storage (Mem0)                                                             │")
    console.print("│  ├─ data/                                                                                  │")
    console.print("│  │  ├─ intent_agent/                                                                       │")
    console.print("│  │  │  ├─ agent_data.json                                                                 │")
    console.print("│  │  │  ├─ analysis_log.jsonl                                                              │")
    console.print("│  │  │  └─ customer_profiles.json                                                          │")
    console.print("│  │  ├─ strategy_agent/                                                                     │")
    console.print("│  │  │  ├─ agent_data.json                                                                 │")
    console.print("│  │  │  ├─ analysis_log.jsonl                                                              │")
    console.print("│  │  │  └─ strategies.json                                                                 │")
    console.print("│  │  ├─ sentiment_agent/                                                                    │")
    console.print("│  │  │  ├─ agent_data.json                                                                 │")
    console.print("│  │  │  ├─ analysis_log.jsonl                                                              │")
    console.print("│  │  │  └─ emotion_tracker.json                                                            │")
    console.print("│  │  ├─ learning_agent/                                                                     │")
    console.print("│  │  │  ├─ agent_data.json                                                                 │")
    console.print("│  │  │  ├─ analysis_log.jsonl                                                              │")
    console.print("│  │  │  └─ learned_patterns.json                                                           │")
    console.print("│  │  ├─ decision_agent/                                                                     │")
    console.print("│  │  │  ├─ agent_data.json                                                                 │")
    console.print("│  │  │  ├─ analysis_log.jsonl                                                              │")
    console.print("│  │  │  └─ decisions.json                                                                  │")
    console.print("│  │  └─ mem0_consolidation/                                                                │")
    console.print("│  │     └─ consolidation_YYYYMMDD_HHMMSS.json                                              │")
    console.print("│                                                                                             │")
    console.print("└─────────────────────────────────────────────────────────────────────────────────────────────┘")
    
    # Stream Processing
    console.print("\n🔄 STREAM PROCESSING ARCHITECTURE:")
    console.print("┌─────────────────────────────────────────────────────────────────────────────────────────────┐")
    console.print("│                                    STREAMING ARCHITECTURE                                  │")
    console.print("├─────────────────────────────────────────────────────────────────────────────────────────────┤")
    console.print("│                                                                                             │")
    console.print("│  🎤 Real-time Audio Stream                                                                 │")
    console.print("│  ├─ Microphone Input (16kHz, Mono)                                                         │")
    console.print("│  ├─ Audio Chunking (512 samples)                                                           │")
    console.print("│  ├─ Base64 Encoding                                                                        │")
    console.print("│  └─ WebSocket Transmission                                                                 │")
    console.print("│                                                                                             │")
    console.print("│  📝 Conversation Stream                                                                     │")
    console.print("│  ├─ User Transcript Events                                                                 │")
    console.print("│  ├─ Agent Response Events                                                                  │")
    console.print("│  ├─ Audio Response Events                                                                  │")
    console.print("│  └─ Ping/Interruption Events                                                               │")
    console.print("│                                                                                             │")
    console.print("│  ⏱️  Window Processing                                                                      │")
    console.print("│  ├─ Time-based Window Triggers (3s/5s/10s)                                                │")
    console.print("│  ├─ Content Sufficiency Checks                                                             │")
    console.print("│  ├─ Cumulative Context Building                                                            │")
    console.print("│  └─ Multi-Agent Analysis Trigger                                                          │")
    console.print("│                                                                                             │")
    console.print("│  🤖 Agent Stream Processing                                                                │")
    console.print("│  ├─ Parallel Agent Execution                                                               │")
    console.print("│  ├─ Independent LLM Calls                                                                  │")
    console.print("│  ├─ Colored Output Logging                                                                 │")
    console.print("│  └─ Memory Persistence                                                                     │")
    console.print("│                                                                                             │")
    console.print("└─────────────────────────────────────────────────────────────────────────────────────────────┘")
    
    # LLM Integration
    console.print("\n🧠 LLM INTEGRATION ARCHITECTURE:")
    console.print("┌─────────────────────────────────────────────────────────────────────────────────────────────┐")
    console.print("│                                    LLM INTEGRATION                                         │")
    console.print("├─────────────────────────────────────────────────────────────────────────────────────────────┤")
    console.print("│                                                                                             │")
    console.print("│  🔵 Quen LLM (Local via Ollama)                                                            │")
    console.print("│  ├─ Intent Agent                                                                           │")
    console.print("│  ├─ Sentiment Agent                                                                        │")
    console.print("│  └─ Decision Agent                                                                         │")
    console.print("│                                                                                             │")
    console.print("│  🟡 GPT-4o (OpenAI API)                                                                    │")
    console.print("│  ├─ Strategy Agent                                                                         │")
    console.print("│  └─ Learning Agent                                                                         │")
    console.print("│                                                                                             │")
    console.print("│  🔄 Fallback Mechanism                                                                     │")
    console.print("│  ├─ Mock Responses for Testing                                                             │")
    console.print("│  ├─ Error Handling                                                                         │")
    console.print("│  └─ Timeout Management                                                                     │")
    console.print("│                                                                                             │")
    console.print("└─────────────────────────────────────────────────────────────────────────────────────────────┘")
    
    # Consolidation Engine
    console.print("\n🧠 MEM0 CONSOLIDATION ENGINE:")
    console.print("┌─────────────────────────────────────────────────────────────────────────────────────────────┐")
    console.print("│                                    CONSOLIDATION PROCESS                                    │")
    console.print("├─────────────────────────────────────────────────────────────────────────────────────────────┤")
    console.print("│                                                                                             │")
    console.print("│  📊 Memory Extraction                                                                       │")
    console.print("│  ├─ Intent Memories                                                                        │")
    console.print("│  ├─ Strategy Memories                                                                      │")
    console.print("│  ├─ Sentiment Memories                                                                     │")
    console.print("│  ├─ Learning Memories                                                                      │")
    console.print("│  └─ Decision Memories                                                                      │")
    console.print("│                                                                                             │")
    console.print("│  🔄 Cross-Agent Analysis                                                                    │")
    console.print("│  ├─ High Confidence Alignments                                                             │")
    console.print("│  ├─ Conflicting Insights                                                                   │")
    console.print("│  ├─ Synergistic Opportunities                                                              │")
    console.print("│  └─ Risk Indicators                                                                        │")
    console.print("│                                                                                             │")
    console.print("│  🎯 Overall Assessment                                                                      │")
    console.print("│  ├─ Overall Confidence Calculation                                                         │")
    console.print("│  ├─ Risk Level Assessment                                                                  │")
    console.print("│  ├─ Opportunity Level Assessment                                                           │")
    console.print("│  └─ Recommended Focus Area                                                                 │")
    console.print("│                                                                                             │")
    console.print("│  📋 Strategic Recommendations                                                               │")
    console.print("│  ├─ Immediate Action Recommendations                                                       │")
    console.print("│  ├─ Intent-based Recommendations                                                           │")
    console.print("│  ├─ Sentiment-based Recommendations                                                        │")
    console.print("│  └─ Strategy-based Recommendations                                                         │")
    console.print("│                                                                                             │")
    console.print("└─────────────────────────────────────────────────────────────────────────────────────────────┘")
    
    # System Components Table
    console.print("\n📋 SYSTEM COMPONENTS SUMMARY:")
    table = Table(title="System Components")
    table.add_column("Component", style="cyan")
    table.add_column("Technology", style="yellow")
    table.add_column("Purpose", style="green")
    table.add_column("Storage", style="magenta")
    
    table.add_row("Intent Agent", "Quen LLM", "Customer intent analysis", "data/intent_agent/")
    table.add_row("Strategy Agent", "GPT-4o", "Strategic recommendations", "data/strategy_agent/")
    table.add_row("Sentiment Agent", "Quen LLM", "Emotional state analysis", "data/sentiment_agent/")
    table.add_row("Learning Agent", "GPT-4o", "Pattern recognition", "data/learning_agent/")
    table.add_row("Decision Agent", "Quen LLM", "Action planning", "data/decision_agent/")
    table.add_row("Mem0 Consolidator", "Custom Logic", "Cross-agent insights", "data/mem0_consolidation/")
    table.add_row("LangGraph Flow", "Async Orchestration", "Parallel execution", "In-memory")
    table.add_row("ElevenLabs Client", "WebSocket", "Real-time communication", "Network")
    table.add_row("Microphone Client", "PyAudio", "Audio capture", "Real-time")
    
    console.print(table)
    
    # Performance Characteristics
    console.print("\n⚡ PERFORMANCE CHARACTERISTICS:")
    console.print("┌─────────────────────────────────────────────────────────────────────────────────────────────┐")
    console.print("│                                    PERFORMANCE METRICS                                     │")
    console.print("├─────────────────────────────────────────────────────────────────────────────────────────────┤")
    console.print("│                                                                                             │")
    console.print("│  ⏱️  Timing:                                                                                │")
    console.print("│  ├─ Window Size: 3s/5s/10s configurable                                                      │")
    console.print("│  ├─ Chunk Delay: 0.05s (optimized)                                                         │")
    console.print("│  ├─ Agent Timeout: 30s per agent                                                            │")
    console.print("│  ├─ Total Analysis Timeout: 120s                                                            │")
    console.print("│  └─ Connection Timeout: 10s                                                                 │")
    console.print("│                                                                                             │")
    console.print("│  🎯 Accuracy:                                                                               │")
    console.print("│  ├─ Intent Confidence: High/Medium/Low                                                      │")
    console.print("│  ├─ Strategy Confidence: High/Medium/Low                                                    │")
    console.print("│  ├─ Sentiment Confidence: Medium (baseline)                                                 │")
    console.print("│  ├─ Learning Confidence: High/Medium/Low                                                    │")
    console.print("│  └─ Decision Confidence: High/Medium/Low                                                    │")
    console.print("│                                                                                             │")
    console.print("│  🔄 Scalability:                                                                            │")
    console.print("│  ├─ Parallel Agent Execution                                                                │")
    console.print("│  ├─ Independent Memory Stores                                                               │")
    console.print("│  ├─ Modular Agent Architecture                                                             │")
    console.print("│  ├─ Configurable Window Sizes                                                              │")
    console.print("│  └─ Extensible Agent System                                                                │")
    console.print("│                                                                                             │")
    console.print("└─────────────────────────────────────────────────────────────────────────────────────────────┘")

if __name__ == "__main__":
    print_system_architecture() 